In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/processed/customer_churn_cleaned.csv")

df.head()

,CustomerID,Gender,Age,SeniorCitizen,Partner,Dependents,TenureMonths,PhoneService,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaymentMethod,MonthlyCharges,TotalCharges,SupportTickets,SatisfactionScore,Churn
0,CUST000001,Female,19,0,Yes,Yes,14,Yes,Cable,No,...,Yes,Yes,Yes,Month-to-month,Electronic Check,63.94,902.51,2,5,Yes
1,CUST000002,Female,55,0,Yes,No,57,No,Fiber Optic,No,...,Yes,No,Yes,Month-to-month,Electronic Check,72.51,4116.15,0,3,No
2,CUST000003,Female,64,1,Yes,No,5,No,Fiber Optic,No,...,Yes,Yes,No,Two year,Credit Card,103.43,561.13,0,4,Yes
3,CUST000004,Female,28,0,No,No,46,No,Fiber Optic,Yes,...,Yes,No,No,Month-to-month,Credit Card,88.81,4107.41,2,1,Yes
4,CUST000005,Female,69,1,No,No,4,Yes,Fiber Optic,No,...,No,No,Yes,Month-to-month,Credit Card,66.66,296.04,1,5,Yes

In [3]:
bins = [0, 12, 24, 48, 72]
labels = ["0-1 Year", "1-2 Years", "2-4 Years", "4-6 Years"]

df["TenureGroup"] = pd.cut(
    df["TenureMonths"],
    bins=bins,
    labels=labels,
    include_lowest=True
)

In [4]:
df["TenureGroup"].value_counts()

TenureGroup
4-6 Years    3349
2-4 Years    3257
0-1 Year     1751
1-2 Years    1643
Name: count, dtype: int64

In [5]:
df["MonthlyChargeCategory"] = pd.qcut(
    df["MonthlyCharges"],
    q=3,
    labels=["Low", "Medium", "High"]
)

In [6]:
df["MonthlyChargeCategory"].value_counts()

MonthlyChargeCategory
Low       3334
Medium    3334
High      3332
Name: count, dtype: int64

In [7]:
df["SupportLevel"] = pd.cut(
    df["SupportTickets"],
    bins=[-1, 1, 3, 10],
    labels=["Low", "Medium", "High"]
)

In [8]:
df["SupportLevel"].value_counts()

SupportLevel
Low       6267
Medium    3313
High       420
Name: count, dtype: int64

In [9]:
df["AverageMonthlySpend"] = (
    df["TotalCharges"] / df["TenureMonths"]
)

In [10]:
df["AverageMonthlySpend"] = (
    df["AverageMonthlySpend"]
    .replace([np.inf, -np.inf], 0)
    .fillna(0)
)

In [11]:
df.head()

,CustomerID,Gender,Age,SeniorCitizen,Partner,Dependents,TenureMonths,PhoneService,InternetService,OnlineSecurity,...,PaymentMethod,MonthlyCharges,TotalCharges,SupportTickets,SatisfactionScore,Churn,TenureGroup,MonthlyChargeCategory,SupportLevel,AverageMonthlySpend
0,CUST000001,Female,19,0,Yes,Yes,14,Yes,Cable,No,...,Electronic Check,63.94,902.51,2,5,Yes,1-2 Years,Medium,Medium,64.465000
1,CUST000002,Female,55,0,Yes,No,57,No,Fiber Optic,No,...,Electronic Check,72.51,4116.15,0,3,No,4-6 Years,High,Low,72.213158
2,CUST000003,Female,64,1,Yes,No,5,No,Fiber Optic,No,...,Credit Card,103.43,561.13,0,4,Yes,0-1 Year,High,Low,112.226000
3,CUST000004,Female,28,0,No,No,46,No,Fiber Optic,Yes,...,Credit Card,88.81,4107.41,2,1,Yes,2-4 Years,High,Medium,89.291522
4,CUST000005,Female,69,1,No,No,4,Yes,Fiber Optic,No,...,Credit Card,66.66,296.04,1,5,Yes,0-1 Year,Medium,Low,74.010000

In [12]:
df.columns

Index(['CustomerID', 'Gender', 'Age', 'SeniorCitizen', 'Partner', 'Dependents',
       'TenureMonths', 'PhoneService', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaymentMethod', 'MonthlyCharges',
       'TotalCharges', 'SupportTickets', 'SatisfactionScore', 'Churn',
       'TenureGroup', 'MonthlyChargeCategory', 'SupportLevel',
       'AverageMonthlySpend'],
      dtype='str')

In [13]:
df.to_csv(
    "../data/processed/customer_churn_feature_engineered.csv",
    index=False
)

# Feature Engineering Summary

## New Features Created

- TenureGroup
- MonthlyChargeCategory
- SupportLevel
- SatisfactionLevel
- AverageMonthlySpend

## Purpose

These features capture customer behavior in a more meaningful way than the raw values alone. They may improve model performance and make the model's decisions easier to interpret.